version: "3.9"

services:
  api:
    build: .
    image: newpakorn/tomato-food-delivery-api:v1.4
    container_name: tomato-api
    env_file:
      - .env
    ports:
      - '5180:5180'
    networks:
      - mynetwork
    volumes:
      - /var/www/myapp/uploads:/app/uploads
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    labels:
    - "com.docker.logging.driver=loki"
    - "com.docker.logging.loki.url=http://loki:3100"
    - "com.docker.logging.loki-retries=5"
    - "com.docker.logging.loki-batch-size=400"
    - "container_name=tomato-api"

networks:
  mynetwork:
    driver: bridge
