version: "3.9"

services:
  api:
    build: .
    image: newpakorn/tomato-food-delivery-api:v1.0
    env_file:
      - .env
    ports:
      - '5180:5180'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
